compiler/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('compilerapp/', include('compilerapp.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

compilerapp/urls.py
from django.urls import path, include

from . import views

app_name = 'compilerapp'
urlpatterns = [
    path('', views.index, name='index'),
    path('add_catalog/', views.add_catalog, name='add_catalog'),
    path('add_file/', views.add_file, name='add_file'),
    path('delete_file/', views.delete_file, name='delete_file'),
    path('delete_catalog/', views.delete_catalog, name='delete_catalog'),
    path('compile/', views.compile, name='compile'),
    path('compile_and_save/', views.compile_and_save, name='compile_and_save'),
    # path('file_contents/<int:catalog_id>/<int:file_id>/', views.file_contents, name='file_contents'),
    # path('open_file/', views.open_file, name='open_file'),
]

compilerapp/models.py
from django.db import models
from datetime import datetime

class User(models.Model):
    username = models.CharField(max_length=255)
    password = models.CharField(max_length=255)

class Catalog(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    is_deleted = models.BooleanField(default=False)
    deleted_at = models.DateTimeField(null=True, blank=True)
    last_modified = models.DateTimeField(auto_now=True)
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE, null=True, blank=True)
    parent = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True)

    def return_nested_objects(self):
        catalogs = Catalog.objects.filter(parent=self)
        files = File.objects.filter(catalog=self)
        return [catalogs, files]
    
    def delete(self):
        self.is_deleted = True
        self.deleted_at = datetime.now()
        for catalog in Catalog.objects.filter(parent=self):
            catalog.delete()
        for file in File.objects.filter(catalog=self):
            file.delete()
        self.save()

class File(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    is_deleted = models.BooleanField(default=False)
    deleted_at = models.DateTimeField(null=True, blank=True)
    last_modified = models.DateTimeField(auto_now=True)
    content = models.TextField(null=True, blank=True)
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE, null=True, blank=True)

    catalog = models.ForeignKey(Catalog, on_delete=models.CASCADE)


class SectionStatusData(models.Model):
    info = models.TextField(null=True, blank=True)
    info_start_line = models.IntegerField(null=True, blank=True)
    info_end_line = models.IntegerField(null=True, blank=True)


class Section(models.Model):
    name = models.CharField(max_length=255, null=True, blank=True)
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    start_line = models.IntegerField()
    end_line = models.IntegerField()
    SECTION_TYPE_CHOICES = [
        ('prc', 'PROCEDURE'),
        ('cm', 'COMMENT'),
        ('dir', 'DIRECTIVES'),
        ('dec', 'DECLARATIONS'),
        ('as', 'ASSEMBLY'),
    ]
    SECTION_STATUS_CHOICES = [
        ('ok', 'OK'),
        ('err', 'ERROR'),
        ('warn', 'WARNING'),
    ]
    section_type = models.CharField(max_length=255, choices=SECTION_TYPE_CHOICES, default='prc')
    section_status = models.CharField(max_length=255, choices=SECTION_STATUS_CHOICES, default='ok')
    section_status_data = models.ForeignKey(SectionStatusData, on_delete=models.CASCADE, null=True, blank=True)
    file = models.ForeignKey(File, on_delete=models.CASCADE, null=True, blank=True)

compilerapp/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404

from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.contrib.sessions.backends.db import SessionStore
from django.http import FileResponse
from .models import Catalog, File, Section

from datetime import datetime
import subprocess
import os

from django.contrib.auth.decorators import login_required

@login_required
def index(request):
    session = SessionStore(request.session.session_key)
    # catalogs = Catalog.objects.all()
    root = Catalog.objects.filter(parent=None, is_deleted=False, user=request.user)
    if (len(root) != 1):
        root = Catalog.objects.create(name='root', parent=None, user=request.user)
        root.save()
    else:
        root = root[0]
    file_tree = root.return_nested_objects()
    context = {
        'file_tree': file_tree,
        'root': root,
    }
    if "result" in session:
        context.update({'compiled': session['result']})
    if request.method == 'POST':
        if "file" in request.POST:
            file_id = request.POST['file']
            if "file_id" in session and file_id != session['file_id']:
                session['result'] = None
                context.update({'compiled': None})
            session['file_id'] = file_id
            file = File.objects.get(id=file_id)
            file_content = file.content
            session['file_content'] = file_content
        if "standard" in request.POST:
            session['standard'] = request.POST['standard']
            # context.update({'standard': request.POST['standard']})
        if "optymalization" in request.POST:
            session['selected_optymalizations'] = request.POST.getlist('optymalization')
        if "procesor" in request.POST:
            session['procesor'] = request.POST['procesor']
        if "procesor_options" in request.POST:
            session['procesor_options'] = request.POST.getlist('procesor_options')

    # Retrieve the stored data from the session
    if "standard" in session:
        context.update({'standard': session['standard']})

    if "selected_optymalizations" in session:
        context.update({'selected_optymalizations': session['selected_optymalizations']})

    if "file_content" in session:
        context.update({'file_content': session['file_content']})

    if "procesor" in session:
        context.update({'procesor': session['procesor']})

    if "procesor_options" in session:
        context.update({'procesor_options': session['procesor_options']})
    
    session.save()
     
    return render(request, 'index.html', context)

@login_required
def add_catalog(request):
    if request.method == 'GET':
        context = {
            'catalogs': Catalog.objects.filter(user=request.user),
        }
        return render(request, 'add_catalog.html', context)
    elif request.method == 'POST':
        name = request.POST['catalog_name']
        description = request.POST['catalog_description']
        parent = request.POST['parent_catalog']
        if name == '' or parent == '':
            return HttpResponseRedirect(reverse('compilerapp:index'))
        else:
            parent = Catalog.objects.get(id=parent)
        catalog = Catalog.objects.create(name=name, description=description, parent=parent, user=request.user)
        catalog.save()
        return HttpResponseRedirect(reverse('compilerapp:index'))
    
@login_required
def add_file(request):
    if request.method == 'GET':
        context = {
            'catalogs': Catalog.objects.filter(user=request.user),
        }
        return render(request, 'add_file.html', context)
    elif request.method == 'POST':
        name = request.POST['file_name']
        description = request.POST['file_description']
        catalog = request.POST['parent_catalog']
        content = request.POST['file_content']
        if catalog == '' or name == '':
            return HttpResponseRedirect(reverse('compilerapp:index'))
        else:
            catalog = Catalog.objects.get(id=catalog)
        file_to_create = File.objects.create(name=name, description=description, catalog=catalog, user=request.user, content=content)
        file_to_create.save()
        return HttpResponseRedirect(reverse('compilerapp:index'))
    
@login_required
def delete_file(request):
    if request.method == 'GET':
        context = {
            'files': File.objects.filter(user=request.user),
        }
        return render(request, 'delete_file.html', context)
    elif request.method == 'POST':
        file_id = request.POST['file_to_delete']
        file_to_delete = File.objects.get(id=file_id)
        file_to_delete.deleted_at = datetime.now()
        file_to_delete.is_deleted = True
        file_to_delete.save()
        return HttpResponseRedirect(reverse('compilerapp:index'))
    
@login_required
def delete_catalog(request):
    if request.method == 'GET':
        context = {
            'catalogs': Catalog.objects.filter(user=request.user),
        }
        return render(request, 'delete_catalog.html', context)
    elif request.method == 'POST':
        catalog_id = request.POST['catalog_to_delete']
        catalog_to_delete = Catalog.objects.get(id=catalog_id)
        catalog_to_delete.delete()
        catalog_to_delete.save()
        return HttpResponseRedirect(reverse('compilerapp:index'))
    
@login_required
def compile(request):
    session = SessionStore(request.session.session_key)
    standard = "--std-" + session['standard']
    selected_optymalizations = session['selected_optymalizations']
    file_id = session['file_id']
    file_to_compile = File.objects.get(id=file_id)
    file_content = file_to_compile.content
    procesor = session['procesor']
    procesor_options = session['procesor_options']
    procesor = procesor.lower()
    cmd = ["sdcc", "-S", "-m" + procesor, standard]
    cmd.extend(selected_optymalizations)
    cmd.extend(procesor_options)

    file_name = f"{request.user.id}.c"
    asm_name = f"{request.user.id}.asm"
    tmp = open(file_name, "w")
    if file_content != None:
        tmp.write(file_content)
        tmp.close()
        cmd.append(file_name)
    
    res = subprocess.run(cmd, capture_output=True, text=True)
    if res.returncode == 0:
        tmp = open(asm_name, "r")
        session['result'] = tmp.read()
        tmp.close()
        os.remove(asm_name)
    else:
        session['result'] = res.stderr
    
    os.remove(file_name)
    session.save()

    return render(request, 'index.html')    

def compile_and_save(request):
    session = SessionStore(request.session.session_key)
    standard = "--std-" + session['standard']
    selected_optymalizations = session['selected_optymalizations']
    file_id = session['file_id']
    file_to_compile = File.objects.get(id=file_id)
    file_content = file_to_compile.content
    procesor = session['procesor']
    procesor_options = session['procesor_options']
    procesor = procesor.lower()
    cmd = ["sdcc", "-S", "-m" + procesor, standard]
    cmd.extend(selected_optymalizations)
    cmd.extend(procesor_options)

    file_name = f"{request.user.id}.c"
    asm_name = f"{request.user.id}.asm"
    tmp = open(file_name, "w")
    if (file_content != None):
        tmp.write(file_content)
    tmp.close()
    cmd.append(file_name)
    
    res = subprocess.run(cmd, capture_output=True, text=True)
    if res.returncode == 0:
        tmp = open(asm_name, "r")
        session['result'] = tmp.read()
        tmp.close()

    # Open the file
        file = open(asm_name, 'rb')

        # Create a FileResponse object
        response = FileResponse(file)

        # Set the content type as the file's MIME type
        response['Content-Type'] = 'application/pdf'  # Replace with the appropriate MIME type

        # Set the Content-Disposition header to force the browser to download the file
        response['Content-Disposition'] = 'attachment; filename="file.asm"'  # Replace with the desired file name

        # Optionally, you can set the Content-Length header if you know the file size
        response['Content-Length'] = os.path.getsize(asm_name)

        os.remove(asm_name)
        os.remove(file_name)
        session.save()
        return response
    else:
        session['result'] = res.stderr
    
    os.remove(file_name)
    session.save()
    response = FileResponse()
    return response

compilerapp/templates/add_catalog.html
<form method="post">
    {% csrf_token %}
    <label for="parent_catalog">Parent catalog:</label>
    <select name="parent_catalog" id="parent_catalog">
      <option value="">---</option>
      {% for catalog in catalogs %}
        {% if catalog.is_deleted == False %}
            <option value="{{ catalog.id }}">{{ catalog.name }}</option>
        {% endif %}
      {% endfor %}
    </select><br><br>
    <label for="catalog_name">Catalog name:</label>
    <input type="text" name="catalog_name" id="catalog_name"><br><br>
    <label for="catalog_description">Catalog description:</label>
    <textarea name="catalog_description" id="catalog_description"></textarea><br><br>
    <input type="submit" value="Add catalog">
</form>
  

compilerapp/templates/add_file.html
<form method="post">
    {% csrf_token %}
    <label for="parent_catalog">Parent catalog:</label>
    <select name="parent_catalog" id="parent_catalog">
      <option value="">---</option>
      {% for catalog in catalogs %}
        {% if catalog.is_deleted == False %}
            <option value="{{ catalog.id }}">{{ catalog.name }}</option>
        {% endif %}
      {% endfor %}
    </select><br><br>
    <label for="file_name">File name:</label>
    <input type="text" name="file_name" id="file_name"><br><br>
    <label for="file_description">File description:</label>
    <textarea name="file_description" id="file_description"></textarea><br><br>
    <label for="file_content">File content:</label>
    <textarea name="file_content" id="file_content"></textarea><br><br>
    <input type="submit" value="Add file">
</form>
  

compilerapp/templates/catalog.html
{% if catalog %}
    <li class="file-tree">
        {% if catalog.is_deleted == False %}
            <a class="catalog">{{ catalog.name }}/</a><button name="delete-catalog" class="delete" type="submit">x</button>
        {% endif %}
        <ul>
            {% for subcatalog in catalog.catalog_set.all %}
            {% if subcatalog.is_deleted == False %}
                {% include 'catalog.html' with catalog=subcatalog %}
            {% endif %}
            {% endfor %}
            <form method="POST">
            {% csrf_token %}
            {% for file in catalog.file_set.all %}
                {% if file.is_deleted == False %}
                    <li class="file-tree-entry"><a class="file"><button name="file" class="file-button" type="submit" value="{{file.id}}">{{ file.name }}</button><button name="delete-file" class="delete" type="submit">x</button></a></li>
                {% endif %}
            {% endfor %}
            </form>
        </ul>
    </li>
{% endif %}

compilerapp/templates/delete_catalog.html
<form method="post">
    {% csrf_token %}
    <ul>
        {% for catalog in catalogs %}
        {% if catalog.is_deleted == False and catalog.name != "root" %}
            <li>
                <strong>Catalog Name:</strong> {{ catalog.name }}<br>
                <strong>Parent Catalog:</strong> {{ catalog.parent_catalog }}<br>
                <strong>Catalog Description:</strong> {{ catalog.description }}<br>
                <input type="radio" name="catalog_to_delete" value="{{ catalog.id }}"> Delete
            </li>
        {% endif %}
        {% endfor %}
    </ul>

    <input type="submit" value="Delete selected catalog">
</form>

compilerapp/templates/delete_file.html
<form method="post">
{% csrf_token %}
<ul>
    {% for file in files %}
        {% if file.is_deleted == False %}
        <li>
            <strong>File Name:</strong> {{ file.name }}<br>
            <strong>Parent Catalog:</strong> {{ file.parent_catalog }}<br>
            <strong>File Description:</strong> {{ file.description }}<br>
            <strong>File Content:</strong> {{ file.content }}<br>
            <input type="radio" name="file_to_delete" value="{{ file.id }}"> Delete
        </li>
        {% endif %}
    {% endfor %}
</ul>

<input type="submit" value="Delete selected files">
</form>

compilerapp/templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>SDCC Compiler</title>
    <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="{% static 'compilerapp/page.css' %}">
    <link rel="stylesheet" href="{% static 'compilerapp/grid.css' %}">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.62.3/codemirror.min.css">
  	<script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.62.3/codemirror.min.js"></script>
 	<script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.62.3/mode/javascript/javascript.min.js"></script>
	<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/js-cookie/3.0.1/js.cookie.min.js"></script>
</head>

<body>
    <div class="container">
        <div class="item" id="action-options">
            <ul class="horizontal">
                <li class="horizontal" id="add-file">
                    <a href="{% url 'compilerapp:add_file' %}" id="add-file">Add File</a>
                </li>
            </ul>
            <ul class="horizontal">
                <li class="horizontal" id="add-catalog">
                    <a href="{% url 'compilerapp:add_catalog' %}" id="add-catalog">Add Catalog</a>
                </li>
            </ul>
			<ul class="horizontal">
                <li class="horizontal" id="remove_file">
                    <a href="{% url 'compilerapp:delete_file' %}" id="remove">Delete File</a>
                </li>
            </ul>
			<ul class="horizontal">
                <li class="horizontal" id="remove_catalog">
                    <a href="{% url 'compilerapp:delete_catalog' %}" id="remove">Delete Catalog</a>
                </li>
            </ul>
			<ul class="horizontal">
                <li class="horizontal">
                    <a href="#" id="compile">Compile</a>
                </li>
            </ul>
			<ul class="horizontal">
                <li class="horizontal">
                    <a href="{% url 'compilerapp:compile_and_save' %}" id="compile_and_save">Save Compiled</a>
                </li>
            </ul>
            <ul class="horizontal">
                <li class="horizontal">Edit</li>
            </ul>
            <ul class="horizontal">
                <li class="horizontal">Options</li>
            </ul>
        </div>

		<!-- <textarea class="item" id="file-text">{{ file_content }}</textarea> -->
		<textarea id="file-text"></textarea>
        <div class="item" id="file-tree">
        	<ul class="vertical">
				{% include 'catalog.html' with catalog=root %}
          	</ul>
        </div>

        <div class="change-theme">
            <button type="button" id="switch" onclick="toggleTheme()">Switch</button>
        </div>


    <textarea class="item" id="file-fragment">{% if compiled %}{{ compiled }}{% endif %}</textarea>

        <div class="item" id="tab-space">
            <div class="tab" onclick="displayTab(event, '1')">STANDARD</div>
            <div class="tab" onclick="displayTab(event, '2')">OPTYMALIZACJE</div>
            <div class="tab" onclick="displayTab(event, '3')">PROCESOR</div>
            <div class="tab" onclick="displayTab(event, '4')">ZALEŻNE</div>
        </div>

        <div class="item" id="tab-content">

			<div class="tab-content" id="1">
				<form method="post">
					{% csrf_token %}
					<select name="standard" id="standard">
					  <option value="c89">C89</option>
					  <option value="c99">C99</option>
					  <option value="c11">C11</option>
					</select>
					<br>
					<input type="submit" value="Save">
				  </form>
			</div>

			<div class="tab-content" id="2">
				<form method="POST">
					  {% csrf_token %}
					  <input type="checkbox" value="--nogcse" name="optymalization">--nogcse</option><br>
					  <input type="checkbox" value="--noinvariant" name="optymalization">--noinvariant</option><br>
					  <input type="checkbox" value="--noinduction" name="optymalization">--noinduction</option><br>
					  <input type="submit" value="Save">
				</form>
			</div>

			<div class="tab-content" id="3">
				<form method="post">
					{% csrf_token %}
					<select name="procesor" id="procesor">
					  <option value="MCS51">MCS51</option>
					  <option value="Z80">Z80</option>
					  <option value="STM8">STM8</option>
					</select>
					<br>
					<input type="submit" value="Save">
				</form>
			</div>

			<div class="tab-content" id="4">

				{% if procesor %}
					{% if procesor == 'MCS51' %}
						<div class="procesor_options">Options for MCS51
							<form method="POST">
								{% csrf_token %}
								<input type="checkbox" value="--model-small" name="procesor_options">--model-small<br>
								<input type="checkbox" value="--model-medium" name="procesor_options">--model-medium<br>
								<input type="checkbox" value="--model-large" name="procesor_options">--model-large<br>
								<input type="submit" value="Save">
							</form>
						</div>
					{% elif procesor == 'Z80' %}
						<div class="procesor_options">Options for Z80
							<form method="POST">
								{% csrf_token %}
								<input type="checkbox" value="--portmode=z80" name="procesor_options">--portmode=z80</option><br>
								<input type="checkbox" value="--portmode=z180" name="procesor_options">--portmode=z180</option><br>
								<input type="checkbox" value="--fno-omit-frame-pointer" name="procesor_options">--fno-omit-frame-pointer</option><br>
								<input type="submit" value="Save">
							</form>
						</div>
					{% elif procesor == 'STM8' %}
						<div class="procesor_options">Options for STM8
							<form method="POST">
								{% csrf_token %}
								<input type="checkbox" value="--model-medium" name="procesor_options">--model-medium<br>
								<input type="checkbox" value="--model-large" name="procesor_options">--model-large<br>
								<input type="checkbox" value="--out-fmt-elf" name="procesor_options">--out-fmt-elf<br>
								<input type="submit" value="Save">
							</form>
						</div>
					{% endif %}
				{% endif %}

				<div id="options-container"></div>
			</div>
		</div>
    </div>
    <script src="{% static 'compilerapp/main.js' %}"></script>

	<script>
		var codeEditor = CodeMirror.fromTextArea(document.getElementById("file-text"), {
		  lineNumbers: true,
		  mode: "javascript"
		});
		codeEditor.setSize("100%", "100%");
		codeEditor.setValue(`{{ file_content }}`);
	</script>
</body>

</html>

compilerapp/templates/open_file.html
<form method="POST">
    {% csrf_token %}
    <label for="file_name">File Name:</label>
    <input type="text" id="file_name" name="file_name">
    <br><br>
    <label for="catalog_name">Catalog Name:</label>
    <input type="text" id="catalog_name" name="catalog_name">
    <br><br>
    <input type="submit" value="Submit">
</form>